try{
    printMessage('Hello')
}catch (e) {
    console.log("error : ",e )
}

console.log('program finished')